// Copyright 2013
// Ubiquitous Knowledge Processing (UKP) Lab
// Technische Universität Darmstadt
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_testing]]
= Testing

The testing module offers a convenient way to create unit tests for UIMA components.

== Basic test setup

There are a couple of things useful in every unit test:

* Redirecting the UIMA logging through log4j - DKPro Core uses log4j for logging in unit tests.
* Printing the name of the test to the console before every test
* Enabling extended index checks in UIMA (`uima.exception_when_fs_update_corrupts_index`)

To avoid repeating a longish setup boilerplate code in every unit test, add the following lines to
your unit test class:

[source,java]
----
@Rule
public DkproTestContext testContext = new DkproTestContext();
----

Additional benefits you get from this `testContext` are:

* getting the class name of the current test (`getClassName()`)
* getting the method name of the current test (`getMethodName()`)
* getting the name of a folder you can use to store test results (`getTestOutputFolder()`).

== Unit test example

A typical unit test class has consists of two parts

. the test cases
. a `runTest` method - which sets up the pipeline required by the
                    test and then calls `TestRunner.runTest()`.

In the following example, mind that the text must be provided with spaces
separating the tokens (thus there must be a space before the full stop at the end of the
sentence) and with newline characters (`\n`) separating the sentences:

.Typical unit test for an analysis component from the OpenNlpNamedEntityRecognizer test (shortened)
[source,java,indent=0]
----
include::{source-dir}de.tudarmstadt.ukp.dkpro.core.opennlp-asl/src/test/java/de/tudarmstadt/ukp/dkpro/core/opennlp/OpenNlpNamedEntityRecognizerTest.java[tags=test]
----

Test cases for segmenter components should not make use of the `TestRunner`
class, which already performs tokenization and sentence splitting internally.

== AssertAnnotations

The AssertAnnotations class offers various static methods to test if a component has
properly created annotations of a certain kind. There are methods to test almost every kind
of annotation supported by DKPro Core, e.g.:

* `assertToken`
* `assertSentence`
* `assertPOS`
* `assertLemma`
* `assertMorph`
* `assertStem`
* `assertNamedEntity`
* `assertConstituents`
* `assertChunks`
* `assertDependencies`
* `assertPennTree`
* `assertSemanticPredicates`
* `assertSemanticField`
* `assertCoreference`
* `assertTagset`
* `assertTagsetMapping`
* `assertValid` - Tests implemented with `TestRunner` and `IOTestRunner` perform validation checks
   automatically. All other unit tests should invoke `AssertAnnotations.assertValid(jcas)`.
* etc.


== Testing I/O componets

The IOTestRunner class offers convenient methods to test I/O components:

* `testRoundTrip` can be used to test converting a format to CAS, converting it back and comparing
  it to the original
* `testOneWay` instead is useful to read data and compare it to a reference file in a different
  format (e.g. CasDumpWriter format). It can also be used if there a full round-trip is not possible
  because some information is lost or cannot be exported exactly as ingested from the original file.

The input file and reference file path given to these methods is always considered relative to
`src/test/resources`.

.Example using `testRoundTrip` with extra parameters (Conll2006ReaderWriterTest)
[source,java,indent=0]
----
include::{source-dir}de.tudarmstadt.ukp.dkpro.core.io.conll-asl/src/test/java/de/tudarmstadt/ukp/dkpro/core/io/conll/Conll2006ReaderWriterTest.java[tags=testRoundTrip]
----

.Example using `testOneWay` with extra parameters (Conll2006ReaderWriterTest)
[source,java,indent=0]
----
include::{source-dir}de.tudarmstadt.ukp.dkpro.core.io.conll-asl/src/test/java/de/tudarmstadt/ukp/dkpro/core/io/conll/Conll2006ReaderWriterTest.java[tags=testOneWay]
----

.Example using `testRoundTrip` with extra parameters (BratReaderWriterTest)
[source,java,indent=0]]
----
include::{source-dir}de.tudarmstadt.ukp.dkpro.core.io.brat-asl/src/test/java/de/tudarmstadt/ukp/dkpro/core/io/brat/BratReaderWriterTest.java[tags=testOneWay]
----
