// Copyright 2013
// Ubiquitous Knowledge Processing (UKP) Lab
// Technische Universität Darmstadt
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[ugr.dkpro.core.testing]]
== Testing

The testing module offers a convenient way to create unit tests for UIMA components.

=== Basic test setup

There are a couple of things useful in every unit test:

* Redirecting the UIMA logging through log4j - DKPro Core uses log4j for logging in unit tests.
* Printing the name of the test to the console before every test
* Enabling extended index checks in UIMA (`uima.exception_when_fs_update_corrupts_index`)

To avoid repeating a longish setup boilerplate code in every unit test, add the following lines to
your unit test class:

[source,java]
----
@Rule
public DkproTestContext testContext = new DkproTestContext();
----

Additional benefits you get from this `testContext` are:

* getting the class name of the current test (`getClassName()`)
* getting the method name of the current test (`getMethodName()`)
* getting the name of a folder you can use to store test results (`getTestOutputFolder()`).

=== Unit test example

A typical unit test class has consists of two parts

. the test cases
. a `runTest` method - which sets up the pipeline required by the
                    test and then calls `TestRunner.runTest()`.

In the following example, mind that the text must be provided with spaces
separating the tokens (thus there must be a space before the full stop at the end of the
sentence) and with newline characters (`\n`) separating the sentences:

.Typical unit test for an analysis component
[source,java]
----
@Rule
public DkproTestContext testContext = new DkproTestContext();

@Test
public void testEnglish() throws Exception
{   
  JCas jcas = runTest("en", null, "This is a test .");

  String[] constituentMapped =
    { "NP 0,4", "NP 8,14", "ROOT 0,16", "S 0,16", "VP 5,14" };

  String[] constituentOriginal = 
    { "NP 0,4", "NP 8,14", "ROOT 0,16", "S 0,16","VP 5,14" };

  String pennTree = "(ROOT (S (NP (DT This)) (VP (VBZ is) " +
    "(NP (DT a) (NN test))) (. .)))";

  String[] constituentTags = 
    { "ADJP", "ADV", "ADVP", "AUX", "CONJP", "FRAG", "INTJ", 
      "LST", "NAC", "NEG", "NP", "NX", "O", "PP", "PRN", "PRT",
      "QP", "S", "SBAR", "SQ", "TYPO", "UCP", "UH", "VP", 
      "WHADJP", "WHADVP", "WHNP", "WHPP", "X" };

  String[] unmappedConst = 
    { "ADV", "AUX", "NEG", "O", "TYPO", "UH" };
        
  AssertAnnotations.assertPennTree(
    pennTree, selectSingle(jcas, PennTree.class));
  AssertAnnotations.assertConstituents(
    constituentMapped, constituentOriginal, 
    select(jcas, Constituent.class));
  AssertAnnotations.assertTagset(
    Constituent.class, "ptb", constituentTags, jcas);
  AssertAnnotations.assertTagsetMapping(
    Constituent.class, "ptb", unmappedConst, jcas);
}

private JCas runTest(String aLanguage, String aVariant, String aDocument)
  throws Exception
{
  AnalysisEngineDescription parser = createEngineDescription(
    OpenNlpParser.class,
    OpenNlpParser.PARAM_VARIANT, aVariant,
    OpenNlpParser.PARAM_PRINT_TAGSET, true,
    OpenNlpParser.PARAM_WRITE_PENN_TREE, true);
  return TestRunner.runTest(parser, aLanguage, aDocument);
}

Test cases for segmenter components should not make use of the `TestRunner`
class, which already performs tokenization and sentence splitting internally.

=== AssertAnnotations

The AssertAnnotations class offers various static methods to test if a component has
properly created annotations of a certain kind. There are methods to test almost every kind
of annotation supported by DKPro Core, e.g.:

* `assertToken`
* `assertSentence`
* `assertPOS`
* `assertLemma`
* `assertMorpheme`
* `assertStem`
* `assertNamedEntity`
* `assertConstituents`
* `assertChunks`
* `assertDependencies`
* `assertPennTree`
* `assertSemanticPredicates`
* `assertSemanticField`
* `assertCoreference`
* `assertTagset`
* `assertTagsetMapping`


