<% 
// Copyright 2018
// Ubiquitous Knowledge Processing (UKP) Lab
// Technische Universität Darmstadt
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import org.dkpro.core.doc.Util;
import static groovy.json.StringEscapeUtils.escapeJava;

engines
    .sort { it.value.spec?.metaData?.name ?: it.key }
    .groupBy {it.value.role }
    .sort { it.key != 'Other' ? (it.value.spec?.metaData?.name ?: it.key) : 'Z' }
    .each { group -> 
%>
=== ${group.key}

<% 
def fileSuffix = group.key.replaceAll(' ', '_');
if (new File(project.basedir, 
    "src/main/asciidoc/component-reference/sectionIntro${fileSuffix}.adoc").exists()) { %>
include::{include-dir}sectionIntro${fileSuffix}.adoc[]
<% } %>

.Analysis Components in category ${group.key} (${group.value.size()})
[options="header", cols="1,2"]
|====
|Component|Description

<% group.value.each { %>
|${Util.engineLink(it.key)}
|${Util.shortDesc(it.value.spec.metaData.description)}

<% } %>
|====


<% group.value.each { 
def engine = it.value; %>
[[engine-${ it.key }]]
==== ${it.value.spec?.metaData?.name ?: it.key}

****
[horizontal, role="small"]
Short name::       ${engine.name}
Category::         ${engine.role}
Group{nbsp}ID::    ${engine.groupId}
Artifact{nbsp}ID:: ${engine.artifactId}
Implementation::   ${engine.spec.annotatorImplementationName}
****

.Description
--
++++
${Util.preparePassthrough(engine.spec.metaData.description)}
++++
--

<%
def testClassPath = "${it.value.module}/src/test/java/${it.value.implName.replaceAll('\\.', '/')}Test.java";
def testClass = new File(project.basedir, "../${testClassPath}");
def testClassCode = testClass.exists() ? testClass.text : null;
if (testClass.exists() && testClassCode.contains('tag::example[]')) {
    def lines = testClassCode.readLines();
    def exampleLine = lines.find { it =~ /tag::example\[\]/ };
    def linenumber = lines.indexOf(exampleLine) + 2;
%>
++++
<div style="float:right">
<a href="https://github.com/dkpro/dkpro-core/blob/master/${testClassPath}#L${linenumber}">View on GitHub</a><br/>
</div>
++++

.Example using ${it.key}
[source,java,indent=0]
----
include::${testClass}[tags=example]
----
<%
}
%>

<%
def paramDecls = engine.spec.metaData.configurationParameterDeclarations
    .configurationParameters.sort { it.name }.groupBy { it.name };
def paramValues = engine.spec.metaData.configurationParameterSettings
    .parameterSettings.sort { it.name }.groupBy { it.name };
    
if (paramDecls) { 
%>
.Parameters
[horizontal, role="small"]
<% paramDecls.each { %>
${it.key}::
+
++++
${Util.preparePassthrough(it.value[0].description)}
++++
<% if (!it.value[0].mandatory) { %>Optional -- <% }
%>Type: __${it.value[0].type}<% 
if (it.value[0].multiValued) { %>[]<% } 
%>__ <%
if (paramValues[it.key]) { %> -- 
Default value: `<%
out.print escapeJava((paramValues[it.key][0].value != null ? 
    paramValues[it.key][0].value : 'null') as String).replaceAll('`','{backtick}')   
%>` <% } %>
<% } // paramDecls.each %>
<% } // if (paramDecls) %>

<%
if (engine.inputs || engine.outputs || engine.languages) {
%>

.Capabilities
[cols="1h,2v", role="small"]
|====
| Inputs 
| <% 
if (engine.inputs) { 
  engine.inputs.each { out.println Util.typeLink(it) };
} else { 
  out.println '__none specified__';
}
%>

| Outputs
| <% 
if (engine.outputs) { 
  engine.outputs.each { out.println Util.typeLink(it) };
} else { 
  out.println '__none specified__';
}
%>

| Languages
d| <% 
if (engine.languages) { 
  out.println engine.languages.join(', ');
} else if (engine.models) { 
  out.println '__see available models__';
} else { 
  out.println '__none specified__';
}
%>
|====
<% } // capabilities %>

<%
if (engine.models) { %>
.Models
[options="header", role="small"]
|====
|Language|Variant|Version
<% engine.models.each { model -> %>
|${model.@language}
|${Util.modelLink(model,model.@variant)}
|${model.@version}

<% } // mods.each { model -> %>
|====
<% } // if (mods) %>

<% } // component %>
<% } // component group%>
