<% 
// Copyright 2018
// Ubiquitous Knowledge Processing (UKP) Lab
// Technische Universität Darmstadt
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

def renderLicense(license)
{
  if (license.url) {
     return "link:${license.url}[${license.name}]"
  } else {
     return "${license.name}"
  }
}

def links(dataset)
{
    def html = '++++\n<div style="float:right">\n';
    html += "<a href=\"${dataset.githubUrl}\">Edit on GitHub</a><br/>\n";
    html += '</div>\n++++\n';
    return html;
}

datasets
    .groupBy { it.value.language }
    .sort { it.key }
    .each { language, languageDatasets ->
%>
=== ${language} 
<%
        languageDatasets.each { key, dataset ->
%>
[[dataset-${key}]]
==== ${dataset.name} 

${links(dataset)}

****
[horizontal, role="small"]
ID::          ${key}
Version::     ${dataset.version ?: 'unknown'}
Media type::  ${dataset.mediaType ?: 'unknown'}
Language::    ${dataset.language ?: 'unknown'}
Encoding::    ${dataset.encoding ?: 'unknown'}
URL::         ${dataset.url ?: 'unknown'}
Attribution{empty}footnoteref:[attributionDisclaimer]:: ${dataset.attribution ?: 'unknown'}
License{empty}footnoteref:[licenseDisclaimer]:: <%
  if (dataset.licenses) {
    dataset.licenses.eachWithIndex { license, i ->
      if (i > 0) print ", "
      print "__${renderLicense(license)}__";
    }
  }
  else {
    %>__unknown__<%
  }
%>
****

.Description
${dataset.description ?: ''}

<%
  def licensesWithComments = dataset.licenses.grep { it.comment };
  if (licensesWithComments) {
  %>
.License comments for ${dataset.name}
[options="header", cols="1,2", role="small"]
|====
| License | Comment
  <%
    licensesWithComments.each { license -> 
      print "| ${renderLicense(license)}";
      print "| ${license.comment}"
    }
  %>
|====
  <%
  }
%>

.Artifacts for ${dataset.name}
[options="header", cols="1,2", role="small"]
|====
| Artifact | SHA1
<%
  dataset.artifacts.each { artifactKey, artifact ->
    if (artifact.text) {
      println "| ${artifactKey}"
      println "| __generated__"
    }
    else {
      println "| link:${artifact.url}[${artifactKey}]"
      println "| ${artifact.sha1}"
    }
  }
%>
|====
<%
    }
}
%>
