<% 
import de.tudarmstadt.ukp.dkpro.core.doc.Util;
import static groovy.json.StringEscapeUtils.escapeJava;
import org.apache.commons.lang3.StringUtils;
import groovy.transform.Field;

@Field def poms = [:];

def getName(pom) {
  String name = poms[pom.artifactId.text()].name.text();
  if (name.contains("- IO -")) {
    name = StringUtils.substringAfter(name, "- IO -").trim();
  }
  else if (name.contains("ASL -")) {
    name = StringUtils.substringAfter(name, "ASL -").trim();
  }
  else if (name.contains("GPL -")) {
    name = StringUtils.substringAfter(name, "ASL -").trim();
  }
  else {
    name = name.trim();
  }
  
  // Strip auxiliary information like version, e.g. '(v${solr-solrj.version}) (ASL)'
  if (name.contains('(')) {
    name = name[0..(name.indexOf('(')-1)].trim();
  }
  
  return name;
}

formats.each { id, format -> poms[format.pom.artifactId.text()] = format.pom };

formats.groupBy { getName(it.value.pom) }
        .sort{ it.key.toLowerCase() }
        .each{ name, formatGroup -> %>
        
[[format-${formatGroup.values().first().pom.artifactId.text() }]]
== ${ name }

<%formatGroup.sort { it.key }.each { %>
[[format-${ it.key }]]
=== ${it.key}

****
[horizontal, role="small"]
Group{nbsp}ID::             ${it.value.groupId}
Artifact{nbsp}ID::          ${it.value.artifactId}
****

<% if (new File(project.basedir, 
    "src/main/asciidoc/format-reference/sectionIntro${it.key}.adoc").exists()) { %>
include::{include-dir}sectionIntro${it.key}.adoc[]
<% } %>

<% if (it.value.readerSpec) { %>
[[format-${ it.value.readerClass }]]
[discrete]
==== ${ it.key }Reader

****
[horizontal, role="small"]
Implementation::      ${it.value.readerClass}
****

.Description
--
++++
${Util.preparePassthrough(it.value.readerSpec.metaData.description)}
++++
--

<%
def paramDecls = it.value.readerSpec.metaData.configurationParameterDeclarations
    .configurationParameters.sort { it.name }.groupBy { it.name };
def paramValues = it.value.readerSpec.metaData.configurationParameterSettings
    .parameterSettings.sort { it.name }.groupBy { it.name };
    
if (paramDecls) { 
%>
.Parameters
[horizontal, role="small"]
<% paramDecls.each { %>
${it.key}::
+
++++
${Util.preparePassthrough(it.value[0].description)}
++++
<% if (!it.value[0].mandatory) { %>Optional -- <% }
%>Type: __${it.value[0].type}<% 
if (it.value[0].multiValued) { %>[]<% } 
%>__ <%
if (paramValues[it.key]) { %> -- 
Default value: `<%
out.print escapeJava((paramValues[it.key][0].value != null ? 
    paramValues[it.key][0].value : 'null') as String).replaceAll('`','{backtick}')   
%>` <% } %>
<% } // paramDecls.each %>
<% } // if (paramDecls) %>

<%
def mimetypes = it.value.readerSpec.collectionReaderMetaData?.capabilities?.collect { 
        it.mimeTypesSupported }.flatten().sort().unique();
        
if (mimetypes) {
%>
.Media Types
[options="header", role="small"]
|====
|Media type
<% mimetypes.each { mimetype -> %>
|${mimetype}

<% } // mimetypes.each { mimetype -> %>
|====
<% } // if (mimetypes) %>


<%
def outputs = it.value.readerSpec.collectionReaderMetaData?.capabilities?.collect { 
        it.outputs?.collect { it.name  } }.flatten().sort().unique();

if (outputs) {
%>
.Outputs
[cols="h,v", role="small"]
|====
| Outputs
| <% 
if (outputs) { 
  outputs.each { out.println Util.typeLink(it) };
} else { 
  out.println '__none specified__';
}
%>
|====
<% } // outputs %>

<% } // if (it.value.readerSpec) %>

<% if (it.value.writerSpec) { %>
[[format-${ it.value.writerClass }]]
[discrete]
==== ${ it.key }Writer

****
[horizontal, role="small"]
Implementation::      ${it.value.writerClass}
****

.Description
--
++++
${Util.preparePassthrough(it.value.writerSpec.metaData.description)}
++++
--

<%
def paramDecls = it.value.writerSpec.metaData.configurationParameterDeclarations
    .configurationParameters.sort { it.name }.groupBy { it.name };
def paramValues = it.value.writerSpec.metaData.configurationParameterSettings
    .parameterSettings.sort { it.name }.groupBy { it.name };
    
if (paramDecls) { 
%>
.Parameters
[horizontal, role="small"]
<% paramDecls.each { %>
${it.key}::
+
++++
${Util.preparePassthrough(it.value[0].description)}
++++
<% if (!it.value[0].mandatory) { %>Optional -- <% }
%>Type: __${it.value[0].type}<% 
if (it.value[0].multiValued) { %>[]<% } 
%>__ <%
if (paramValues[it.key]) { %> -- 
Default value: `<%
out.print escapeJava((paramValues[it.key][0].value != null ? 
    paramValues[it.key][0].value : 'null') as String).replaceAll('`','{backtick}')   
%>` <% } %>
<% } // paramDecls.each %>
<% } // if (paramDecls) %>

<%
def mimetypes = it.value.writerSpec.analysisEngineMetaData?.capabilities?.collect { 
        it.mimeTypesSupported }.flatten().sort().unique();

if (mimetypes) {
%>
.Media types
[options="header", role="small"]
|====
|Media type
<% mimetypes.each { mimetype -> %>
|${mimetype}

<% } // mimetypes.each { mimetype -> %>
|====
<% } // if (mimetypes) %>

<%
def inputs = it.value.writerSpec.analysisEngineMetaData?.capabilities?.collect { 
        it.inputs?.collect { it.name  } }.flatten().sort().unique();

if (inputs) {
%>
.Inputs
[cols="h,v", role="small"]
|====
| Inputs 
| <% 
if (inputs) { 
  inputs.each { out.println Util.typeLink(it) };
} else { 
  out.println '__none specified__';
}
%>
|====
<% } // inputs %>

<% } // if (it.value.writerSpec) %>

<% } // format %>

<% } // format group %>
