<% 
// Copyright 2018
// Ubiquitous Knowledge Processing (UKP) Lab
// Technische Universität Darmstadt
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import de.tudarmstadt.ukp.dkpro.core.doc.Util;

def metadataValueText(model, key, value)
{
    if (key.endsWith(".tagset")) {
        def layer = key.tokenize('.')[0];
        def tagset = value;
        def lang = model.@language;
        return "<<tagset-reference.adoc#tagset-${lang}-${tagset}-${layer},${ tagset }>>";
    }
    else {
        return value;
    }
}

def getEngineLink(model) {
    if (model.@engine as String) {
        return Util.engineLink(model.@engine);
    } else {
        return "`${model.@tool}` @ `${model.@package}`";
    } 
}

def getSource(model) {
    def source;
    def getStatement = model.parent().children().find { node -> node.name() in [ 'get' ]};
    if (getStatement?.@src) {
        source = getStatement?.@src.text()
    }
    else {
        source = "No get statement found";
    }
    return source;
}

def renderModel(model) {
%>
[[model-${model.@artifactId}]]
==== ${model.@variant.text() } 

****
[horizontal, role="small"]
Group{nbsp}ID::    ${model.@groupId}
Artifact{nbsp}ID:: ${model.@artifactId}
Version::          ${model.@version}
Engine::           ${getEngineLink(model)}
Language::         ${model.@language}
Variant::          ${model.@variant} <% 
if (getSource(model)) { %>
Source::           ${getSource(model)} <% 
}
if (model.@md5.text()) { %>
MD5::              ${model.@md5.text()}
<% } %>
****


<% if (model.metadata.entry.size() > 0) { %>
.Metadata for ${model.@shortArtifactId} 
[options="header", role="small"]
|====
|Key|Value
<% model.metadata.entry.each { %>
| ${ it.@key }
| ${ metadataValueText(model, it.@key as String, it.@value as String) }
<% } %>
|====
<% } // if (model.metadata.entry) %>
<% 
}
%>

<% 
models
    .findAll { it.@engine as String }
    .groupBy { it.@language.text() }
    .sort { it.key }
    .each { language, languageGroup ->
%>
== ${language} (${languageGroup.size()})
<%
    languageGroup.groupBy { it.@engine.text() }.sort { it.key }.each { engine, engineGroup ->
%>
=== ${engine} (${engineGroup.size()})

<%
        engineGroup.sort { it.@variant.text() }.each { renderModel(it) }
    }
}
%>
