<%
import de.tudarmstadt.ukp.dkpro.core.doc.Util;
import org.dkpro.meta.core.model.EngineModel;
import org.dkpro.meta.core.model.FormatModel;

def isElevatedType(type) {
    // Not a top-level type
    !(type.supertypeName in ['org.apache.uima.jcas.cas.TOP', 'uima.tcas.Annotation']) &&
    // Does not define new features
    type.features.size() == 0;
}

def renderType(type) {
    def shortTypeName = type.name.tokenize('.')[-1];

    if (isElevatedType(type)) {
        out.println("[discrete]");
    }
%>
[[type-${ type.name }]]
==== ${shortTypeName}

****
[horizontal, role="small"]
URI::       http://dkpro.github.io/dkpro-core/releases/${project.version}/docs/typesystem-reference.html#${type.name}
Name::      ${type.name}
Supertype:: ${Util.typeLink(type.supertypeName)}
<%
if (typesystemMappings[type.name]) {
    typesystemMappings[type.name].externalReferences.each { ref ->
        out.println("${ref.rel}:: ${ref.id} (${ref.source})");
    }
}
%>
****

.Description
--
++++
${Util.preparePassthrough(type.description)}
++++
--

<%
    if (type.features) { 
%>
.Features of ${shortTypeName} (${type.features.size()})
<%                  
        type.features.sort { type.name }.each { 
%>
`${it.name}` (__${Util.typeLink(it.rangeTypeName)}__<%
            if (it.elementType) {
                out.print " of ${Util.typeLink(it.elementType)}"
            } 
%>):: ${it.description ?: '__No description__'}
<%                  
        } 
    } // if (type.features) 
%>

.Producers and consumers of ${shortTypeName} 
[cols="1h,2v", role="small"]
|====
|Producers
| <%
    def producers = engines
        .sort{ it.key }
        .findAll { id, engine ->
            engine.spec.analysisEngineMetaData?.capabilities?.any { 
                it.outputs?.any { it.name == type.name } } };
    producers += formats
        .sort{ it.key }
        .findAll { id, format ->
            format.readerSpec?.collectionReaderMetaData?.capabilities?.any { 
                it.outputs?.any { it.name == type.name } } };
    if (producers) {            
        producers.each { id, producer -> 
            if (producer instanceof EngineModel) {
                out.println Util.engineLink(id);
            }
            else {
                out.println "${Util.formatLink(producer)} (format)";
            }
        }
    } else {
        out.println('__None declared__');
    }
%>
|Consumers
| <%
    def consumers = engines
        .sort{ it.key }
        .findAll { engine ->
            engine.value.spec.analysisEngineMetaData?.capabilities?.any { 
                it.inputs?.any { it.name == type.name } } };
    consumers += formats
        .sort{ it.key }
        .findAll { id, format ->
            format.writerSpec?.analysisEngineMetaData?.capabilities?.any { 
                it.inputs?.any { it.name == type.name } } };
    if (consumers) {            
        consumers.each { id, consumer -> 
            if (consumer instanceof EngineModel) {
                out.println Util.engineLink(id);
            }
            else {
                out.println "${Util.formatLink(consumer)} (format)";
            }
        }
    } else {
        out.println('__None declared__');
    }
%>
|====


<%
    def subtypes = typesystems
        .collect { it.types }
        .flatten()
        .sort { it.name.tokenize('.')[-1] }
        .unique { it.name }
        .findAll { it.supertypeName == type.name };
    
    if (subtypes) {
%>
.Sub-types of ${shortTypeName} (${subtypes.size()})
[options="header",cols="1,3", role="small"]
|====
|Type|Description
<%  
        subtypes.each { subtype -> 
%>
|${Util.typeLink(subtype.name)}
|${Util.shortDesc(subtype.description)}
<% 
        } // subtypes.each
%>

|====
<%
    } // if (subtypes)
} // renderType()



typesystems
    .groupBy { it.name }
    .sort { it.key }
    .each { section, sectionTypesystems -> 
%>
=== ${section}

<% if (new File(project.basedir, 
    "src/main/asciidoc/typesystem-reference/sectionIntro${section}.adoc").exists()) { %>
include::{include-dir}sectionIntro${section}.adoc[]
<% } %>

<%
        sectionTypesystems
            .findAll { it.description }
            .each { typesystem ->
%>
++++
${Util.preparePassthrough(typesystem.description)}
++++

<%        
        }
        
        sectionTypesystems
            .collect { it.types }
            .flatten()
            .unique { it.name }
            .findAll { !isElevatedType(it) }
            .sort { it.name.tokenize('.')[-1] }
            .each { renderType(it) }

        sectionTypesystems
            .collect { it.types }
            .flatten()
            .unique { it.name }
            .findAll { isElevatedType(it) }
            .sort { it.name.tokenize('.')[-1] }
            .each { renderType(it) }
} // typesystems 
%>
