// Copyright 2013
// Ubiquitous Knowledge Processing (UKP) Lab
// Technische Universität Darmstadt
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_io]]

== I/O

This section gives an overview on the I/O components. The components are organized into one
module per file type. These modules contain typically one reader and/or writer
component.

All readers initialize the CAS with a DocumentMetaData annotation.

Most readers and writers do not support all features of the respective formats.
Additionally, readers and writers may only support a specific variant of a format.


=== Reading data

DKPro Core aims to provide a consistent API for reading and writing annotated data.
Most of our readers are resource readers (RR) or file writers (FW) and support a common
set of parameters which are explained below.

.Resource reader parameters
[options="header"]
|====
|Parameter|Description|Default
|PARAM_SOURCE_LOCATION
|Location to read from.
|optional

|PARAM_PATTERNS
|Include/exclude patterns.
|optional

|PARAM_USE_DEFAULT_EXCLUDES
|Enable default excludes for versioning systems like Subversion, git, etc.
|true

|PARAM_INCLUDE_HIDDEN
|Include hidden files
|false

|PARAM_LANGUAGE
|Two letter ISO code
|optional
|====

Either `PARAM_SOURCE_LOCATION` or `PARAM_PATTERNS` or both must be set.

.Read all files in the folder __files/texts__
----
PARAM_SOURCE_LOCATION, "files/texts"
----

.Recursively read all __.txt__ files in the folder __files/texts__ (embedded pattern)
----
PARAM_SOURCE_LOCATION, "files/texts/**/*.txt"
----

.Recursively read all __.txt__ files in the folder __files/texts__ (detached pattern)
----
PARAM_SOURCE_LOCATION, "files/texts"
PARAM_PATTERNS, "*.txt"
----

.Excluding some files (detached pattern)
----
PARAM_SOURCE_LOCATION, "files/texts"
PARAM_PATTERNS, new String[] {"*.txt", "[-]broken*.txt"}
----

.Read from the classpath
----
PARAM_SOURCE_LOCATION, "classpath*:texts/*.txt"
----

=== Writing data

.File writer parameters
[options="header"]
|====
| Parameter|Description|Default
| PARAM_TARGET_LOCATION
| Location to write to.
| mandatory

| PARAM_COMPRESSION
| Compression algorithm to use when writing output. File suffix automatically added depending on 
  algorithm. Supported are: NONE, GZIP, BZIP2, and XZ (see class CompressionMethod).
| NONE

| PARAM_FILENAME_EXTENSION
| Append this extension to files names. If PARAM_STRIP_EXTENSION is set to true, the original extension is replaced.
| depends on writer

| PARAM_STRIP_EXTENSION
| Whether to remove the original file extension when writing. E.g. with the XmiWriter without 
  extension stripping, an input file __MyText.txt__ would be written as __MyText.txt.xmi__ - with 
  stripping it would be __MyText.xmi__.
| false

| PARAM_USE_DOCUMENT_ID
| Use the document ID as the file name, even if an original file name is present in the document URI.
| false

| PARAM_ESCAPE_DOCUMENT_ID
| Escape the document ID in case it contains characters that are not valid in a filename.
| false

| PARAM_SINGULAR_TARGET
| Treat target location as a single file name.
| false

| PARAM_OVERWRITE
| Allow overwriting existing files.
| false
|====

=== Working with ZIP archives

Most formats can be read from and written to ZIP archives.

.Read from a ZIP archive
----
PARAM_SOURCE_LOCATION, "jar:file:archive.zip!texts/**/*.txt"
----

Most file writers write multiple files, so `PARAM_TARGET_LOCATION` is treated as a directory
name. A few only write a single file (e.g. NegraExportWriter), in which case the
parameter is treated as the file name. Instead of writing to a directory, it is possible
to write to a ZIP archive:

.Write to a ZIP archive
----
PARAM_TARGET_LOCATION, "jar:file:archive.zip"
----

.Write to a folder inside a ZIP archive
----
PARAM_TARGET_LOCATION, "jar:file:archive.zip!folder/within/zip"
----

NOTE: It is not possible to write into an existing ZIP file. A new file is created in every case. 
      If a ZIP file by the name already exists, it is overwritten.
