// Copyright 2017
// Ubiquitous Knowledge Processing (UKP) Lab
// Technische Universität Darmstadt
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_setup]]
= Setup

== OS X

DKPro Core should work fine without and additional actions on OS X.

== Linux

Some DKPro Core modules may make use of native executables. Since some executables are only
available as 32bit binaries, you may have to install the **32-bit libs on a 64-bit Linux system**.
For example, on Ubuntu this can be done using the following commands

.Ubuntu 12.04 LTS and before (64-bit)
[source]
----
$ sudo apt-get install ia32-libs
----

.Ubuntu 13.04 (64-bit) and later
[source]
----
$ sudo apt-get install lib32z1
----

In both cases, you will have to enter your password and you should restart your computer
afterwards. For other Linux versions, please inform yourself how to install the respective
libraries.

== Windows

Some DKPro Core modules may make use of native executables. In order to use them, you may have
to install the **Microsoft Visual C++ 2010 SP1 Redistributable Package**. Since some executables 
are only available as 32bit binaries, you may have to install the 32bit version of this package
even if you have a 64bit Windows.

* link:https://www.microsoft.com/en-US/download/details.aspx?id=8328[Microsoft Visual C++ 2010 SP1 Redistributable Package (x86)] (32bit)
* https://www.microsoft.com/en-US/download/details.aspx?id=13523[Microsoft Visual C++ 2010 SP1 Redistributable Package (x64)] (64bit)