// Copyright 2013
// Ubiquitous Knowledge Processing (UKP) Lab
// Technische Universität Darmstadt
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[sect_testing]]
= Testing

The testing module offers a convenient way to create unit tests for UIMA components.

== Basic test setup

There are a couple of things useful in every unit test:

* Redirecting the UIMA logging through log4j - DKPro Core uses log4j for logging in unit tests.
* Printing the name of the test to the console before every test
* Enabling extended index checks in UIMA (`uima.exception_when_fs_update_corrupts_index`)

To avoid repeating a longish setup boilerplate code in every unit test, add the following lines to
your unit test class:

[source,java]
----
@Rule
public DkproTestContext testContext = new DkproTestContext();
----

Additional benefits you get from this `testContext` are:

* getting the class name of the current test (`getClassName()`)
* getting the method name of the current test (`getMethodName()`)
* getting the name of a folder you can use to store test results (`getTestOutputFolder()`).

== Unit test example

A typical unit test class has consists of two parts

. the test cases
. a `runTest` method - which sets up the pipeline required by the
                    test and then calls `TestRunner.runTest()`.

In the following example, mind that the text must be provided with spaces
separating the tokens (thus there must be a space before the full stop at the end of the
sentence) and with newline characters (`\n`) separating the sentences:

.Typical unit test for an analysis component from the OpenNlpNamedEntityRecognizer test (shortened)
[source,java,indent=0]
----
include::{source-dir}dkpro-core-opennlp-asl/src/test/java/de/tudarmstadt/ukp/dkpro/core/opennlp/OpenNlpNamedEntityRecognizerTest.java[tags=test]
----

Test cases for segmenter components should not make use of the `TestRunner`
class, which already performs tokenization and sentence splitting internally.

== AssertAnnotations

The AssertAnnotations class offers various static methods to test if a component has
properly created annotations of a certain kind. There are methods to test almost every kind
of annotation supported by DKPro Core, e.g.:

* `assertToken`
* `assertSentence`
* `assertPOS`
* `assertLemma`
* `assertMorph`
* `assertStem`
* `assertNamedEntity`
* `assertConstituents`
* `assertChunks`
* `assertDependencies`
* `assertPennTree`
* `assertSemanticPredicates`
* `assertSemanticField`
* `assertCoreference`
* `assertTagset`
* `assertTagsetMapping`
* `assertValid` - Tests implemented with `TestRunner` and `IOTestRunner` perform validation checks
   automatically. All other unit tests should invoke `AssertAnnotations.assertValid(jcas)`.
* etc.


== Testing I/O componets

The `ReaderAssert` and `WriterAssert` classes can be used to text I/O components. They allow building
AssertJ-style unit tests with DKPro Core reader and writer components.

One of the simplest tests is a *round-trip test* where an input file is read using a reader for a 
particular format, then written out again using a writer for the same format. 

.Example of a round-trip test
[source,java,indent=0]
----
include::{source-dir}dkpro-core-io-conll-asl/src/test/java/de/tudarmstadt/ukp/dkpro/core/io/conll/Conll2006ReaderWriterTest.java[tags=testRoundTrip]
----

The reader is set up to reader the test input file. Instead of setting `PARAM_SOURCE_LOCATION`, it is
also possible to set the input location using `readingFrom()`. The writer automatically makes use of
a test output  folder provided by a `DkproTestContext` - therefore a target location does not need to
be configured explicitly. 

Assuming the writer produces only a single output file, this file can be accessed for
assertions using `outputAsString()`. If multiple output files are created, an argument can be passed
to that method, e.g. `outputAsString("output.txt")`. This will look for a at the target location whose
name ends in `output.txt`. If there is none or more than one matching file, the test will fail.

If the original input file is in a different format or cannot be fully reproduced by the writer,
then it is easy to set up a *one way test*, simply by changing the final comparison. The following
example also shows how to specify additional parameters on the reader or writer.

.Example of a one-way test
[source,java,indent=0]
----
include::{source-dir}dkpro-core-io-conll-asl/src/test/java/de/tudarmstadt/ukp/dkpro/core/io/conll/Conll2006ReaderWriterTest.java[tags=testOneWay]
----

In order to test the ability of readers to read multiple files, the `asJCasList()` method can be used.
While pipelines typically re-use a single CAS which is repeatedly reset and refilled, this method
generates a list of separate CAS instances which can be individually validated after the test. To
access elements of the list use `element(n)`.