The CoNLL 2008 format targets syntactic and semantic dependencies. Columns are tab-separated. Sentences are separated by a blank new line.

.Columns
[cols="3*", options="header"]
|====
| Column  | Type/Feature | Description

| ID      
| ignored 
| Token counter, starting at 1 for each new sentence.

| FORM    
| Token 
| Word form or punctuation symbol.

| LEMMA   
| Lemma 
| Lemma of the word form.

| GPOS  
| POS PosValue 
| Golf fine-grained part-of-speech tag, where the tagset depends on the language.

| PPOS
| ignored
| Automatically predicted major POS by a language-specific tagger.

| SPLIT_FORM   
| ignored 
| Tokens split at hyphens and slashes.

| SPLIT_LEMMA
| ignored
| Predicted lemma of SPLIT_FORM.

| PPOSS
| ignored
| Predicted POS tags of the split forms.

| HEAD    
| Dependency 
| Head of the current token, which is either a value of ID or zero (`0). Note that depending on the original treebank annotation, there may be multiple tokens with an ID of zero.

| DEPREL  
| Dependency 
| Dependency relation to the HEAD. The set of dependency relations depends on the particular language. Note that depending on the original treebank annotation, the dependency relation may be meaningful or simply `ROOT`.

| PRED
| SemPred
| (sense) identifier of a semantic 'predicate' coming from a current token.

| APREDs
| SemArg
| Columns with argument labels for each semantic predicate (in the ID order).
|====
 
.Example
[source,text]
----
1   Some    some    DT  _   Some    some    DT  10  SBJ _   _   _   _   A1  _   _   _
2   of  of  IN  _   of  of  IN  1   NMOD    _   _   _   _   _   _   _   _
3   the the DT  _   the the DT  5   NMOD    _   _   _   _   _   _   _   _
4   strongest   strongest   JJS _   strongest   strong  JJS 5   NMOD    _   _   _   _   _   _   _   _
5   critics critics NNS _   critics critic  NNS 2   PMOD    critic.01   A0  _   _   _   _   _   _
6   of  of  IN  _   of  of  IN  5   NMOD    _   A1  _   _   _   _   _   _
7   our our PRP$    _   our our PRP$    9   NMOD    _   _   A1  A0  _   _   _   _
8   welfare welfare NN  _   welfare welfare NN  9   NMOD    welfare.01  _   A2  _   _   _   _   _
9   system  system  NN  _   system  system  NN  6   PMOD    system.01   _   _   _   _   _   _   _
10  are are VBP _   are be  VBP 0   ROOT    be.01   _   _   _   _   _   _   _
11  the the DT  _   the the DT  12  NMOD    _   _   _   _   _   _   _   _
12  people  people  NNS _   people  people  NNS 10  PRD person.02   _   _   _   A2  A0  A0  A1
13  who who WP  _   who who WP  14  SBJ _   _   _   _   _   _   _   _
14  have    have    VBP _   have    have    VBP 12  NMOD    have.04 _   _   _   _   SU  _   _
15  become  become  VBN _   become  become  VBN 14  VC  become.01   _   _   _   _   A1  A1  _
16  dependent   dependent   JJ  _   dependent   dependent   JJ  15  PRD _   _   _   _   _   _   _   _
17  on  on  IN  _   on  on  IN  16  AMOD    _   _   _   _   _   _   _   _
18  it  it  PRP _   it  it  PRP 17  PMOD    _   _   _   _   _   _   _   _
19  .   .   .   _   .   .   .   10  P   _   _   _   _   _   _   _   _
----

.Known corpora in this format
[cols="2*", options="header"]
|====
| Corpus 
| Language

| link:http://www.anc.org/data/masc/downloads/data-download/[MASC-CONLL]
| English
|====
