// Copyright 2018
// Ubiquitous Knowledge Processing (UKP) Lab
// Technische Universität Darmstadt
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

One of the official formats supported by UIMA is the XMI format. It is an XML-based format that does
not support a few very specific characters which are invalid in XML. But it is able to capture all
the information contained in the CAS. The XMI format is the de-facto standard for exchanging data
in the UIMA world. Most UIMA-related tools support it.

The XMI format does not include type system information. It is therefore recommended to always
configure the XmiWriter component to also write out the type system to a file.

If you with to view annotated documents using the UIMA CAS Editor in Eclipse, you can e.g. set up
your XmiWriter in the following way to write out XMIs and a type system file:

[source,java]
----
AnalysisEngineDescription xmiWriter = 
  AnalysisEngineFactory.createEngineDescription(
      XmiWriter.class, 
      XmiWriter.PARAM_TARGET_LOCATION, ".",
      XmiWriter.PARAM_TYPE_SYSTEM_FILE, "typesystem.xml");  
----
