// Licensed to the Technische Universität Darmstadt under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The Technische Universität Darmstadt 
// licenses this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.
//  
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

NOTE: This is a port of the BioC support from INCEpTION.

NOTE: Support for BioC is quite experimental.

link:http://bioc.sourceforge.net[BioC] is a simple format to share text data and annotations popular in the BioNLP community.

This is a new and still experimental BioC format. 

* Sentence information is supported
  * If sentences are present in a BioC document, they are imported. Otherwise, {product-name} will
    automatically try to determine sentence boundaries.
  * On export, the BioC files are always created with sentence information.
* Passages are imported as a `Div` annotations and the passage `type` infon is set as the `type`
  feature on these `Div` annotations
* When reading span or relation annotations, the `type` infon is used to look up a suitable 
  annotation layer. If a layer exists where either the full technical name of the layer or the
  simple technical name (the part after the last dot) match the type, then an attempt will be made
  to match the annotation to that layer. If the annotation has other infons that match features on
  that layer, they will also be matched.
* When exporting annotations, the `type` infon will always be set to the full layer name and
  features will be serialized to infons matching their names.
* If a document has not been imported from a BioC file containing passages and does not contain
  `Div` annotations from any other source either, then on export a single passage containing the
  entire document is created.
* Cross-passage relations are not supported.
* Sentence-level infons are not supported.
* Passage-level infons are not supported.
* Document-level infons are not supported.
* The writer writes one BioC file per CAS (i.e. writing multiple documents to a single collection file is not supported).
* When reading, the IDs of tokens, sentences and passages are stored to the `id` feature of the respective DKPro Core annotations. The are preserved when writing the data back to files.

 
.Example BioC (excerpt from `sentence.xml` file included in the BioC Java 1.0.1 package)
[source,xml]
----
<?xml version='1.0' encoding='UTF-8'?><!DOCTYPE collection SYSTEM "BioC.dtd">
<collection>
  <source>PubMed</source>
  <date>20120606</date>
  <key>sentence.key</key>
  <document>
    <id>21951408</id>
    <passage>
      <infon key="type">title</infon>
      <offset>0</offset>
      <sentence>
        <offset>0</offset>
        <text>Constraint-induced movement therapy for the upper paretic limb in acute or sub-acute stroke: a systematic review.</text>
      </sentence>
    </passage>
    <passage>
      <infon key="type">abstract</infon>
      <offset>114</offset>
      <sentence>
        <offset>114</offset>
        <text>Constraint-induced movement therapy is a commonly used intervention to improve upper limb function after stroke.</text>
      </sentence>
    </passage>
  </document>
</collection>
----
