/*
 * Licensed to the Technische Universität Darmstadt under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The Technische Universität Darmstadt 
 * licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.
 *  
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.dkpro.core.decompounding.ranking;

import org.dkpro.core.decompounding.splitter.DecompoundedWord;
import org.dkpro.core.decompounding.splitter.DecompoundingTree;
import org.dkpro.core.decompounding.web1t.Finder;

/**
 * The ranking algorithm interface
 */
public interface Ranker
{
    /**
     * Returns the highest ranked split
     *
     * @param splits
     *            A split tree generated by a splitting algorithm
     * @return the highest ranked split
     */
    public DecompoundedWord highestRank(DecompoundingTree splits);

    /**
     * Sets the finder to the ranking algorithm
     * 
     * @param aFinder
     *            the finder.
     */
    public void setFinder(Finder aFinder);

}
